// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngkbxqkdgqisjkbzpdyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5na2J4cWtkZ3Fpc2prYnpwZHl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NTc3ODgsImV4cCI6MjA1ODIzMzc4OH0.nylazB_bV4mnSn1Ag97E70OA_EMKMcC57JWpSsJULmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);